name = "DependencyParser"
uuid = "653b9f5c-1d2a-408c-bb0d-d6dbe2b10d61"
authors = ["Egor Shmorgun"]
version = "0.1.0"

[deps]
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
DependencyParserTest = "3317b7d4-64e8-48d8-a33c-9fcfdad29d0b"
Flux = "587475ba-b771-5e3f-ad9e-33799f191a9c"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
TextAnalysis = "a2db99b7-8b79-58f8-94bf-bbc811eef33d"
TextModels = "77b9cbda-2a23-51df-82a3-24144d1cd378"
WordTokenizers = "796a5d58-b03d-544a-977e-18100b691f6e"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
